version: '3'

services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: 'cleantogather' 
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'root'
    restart: always

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        depends_on:
            - database
        environment:
          PMA_HOST: database


